In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

In [4]:
A = np.array([[4, 1, 7],
              [2, 8, 3],
              [5, 9, 0]])

B = np.array([[2, 6, 1],
              [7, 0, 5],
              [3, 4, 9]])
sum_matrix = A + B
sum_matrix


array([[ 6,  7,  8],
       [ 9,  8,  8],
       [ 8, 13,  9]])

In [5]:
C = np.array([[8, 2],
              [5, 7],
              [3, 9]])

D = np.array([[1, 4],
              [6, 2],
              [0, 5]])
diff_matrix = C - D
diff_matrix


array([[ 7, -2],
       [-1,  5],
       [ 3,  4]])

In [6]:
E = np.array([[2, 0, 3, 1],
              [4, 5, 2, 7],
              [1, 3, 6, 2]])

F = np.array([[3, 1, 2],
              [0, 4, 6],
              [7, 2, 5],
              [1, 8, 3]])
product_matrix = np.dot(E, F)
product_matrix


array([[28, 16, 22],
       [33, 84, 69],
       [47, 41, 56]])

In [7]:
G = np.array([[5, 2, 8, 4],
              [1, 7, 3, 9],
              [6, 0, 5, 2],
              [3, 8, 1, 7]])
transpose_G = G.T
transpose_G


array([[5, 1, 6, 3],
       [2, 7, 0, 8],
       [8, 3, 5, 1],
       [4, 9, 2, 7]])